require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ContentImagesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ContentImage. As you add validations to ContentImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {
    question_image_file_name: 'henk.png',
    answer_image_file_name: 'henk.png',
    filename: 'henk'
  } }

  let(:invalid_attributes) { {
    filename: nil
  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContentImagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all content_images as @content_images" do
      content_image = ContentImage.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:content_images)).to eq([content_image])
    end
  end

  describe "GET #show" do
    it "assigns the requested content_image as @content_image" do
      content_image = ContentImage.create! valid_attributes
      get :show, params: {id: content_image.to_param}, session: valid_session
      expect(assigns(:content_image)).to eq(content_image)
    end
  end

  describe "GET #new" do
    it "assigns a new content_image as @content_image" do
      get :new, params: {}, session: valid_session
      expect(assigns(:content_image)).to be_a_new(ContentImage)
    end
  end

  describe "GET #edit" do
    it "assigns the requested content_image as @content_image" do
      content_image = ContentImage.create! valid_attributes
      get :edit, params: {id: content_image.to_param}, session: valid_session
      expect(assigns(:content_image)).to eq(content_image)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ContentImage" do
        expect {
          post :create, params: {content_image: valid_attributes}, session: valid_session
        }.to change(ContentImage, :count).by(1)
      end

      it "assigns a newly created content_image as @content_image" do
        post :create, params: {content_image: valid_attributes}, session: valid_session
        expect(assigns(:content_image)).to be_a(ContentImage)
        expect(assigns(:content_image)).to be_persisted
      end

      it "redirects to the created content_image" do
        post :create, params: {content_image: valid_attributes}, session: valid_session
        expect(response).to redirect_to(ContentImage.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved content_image as @content_image" do
        post :create, params: {content_image: invalid_attributes}, session: valid_session
        expect(assigns(:content_image)).to be_a_new(ContentImage)
      end

      it "re-renders the 'new' template" do
        post :create, params: {content_image: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_filename) { "other_filename" }
      let(:new_attributes) {
        valid_attributes.tap do |attrs|
          attrs[:filename] = new_filename
        end
      }

      it "updates the requested content_image" do
        content_image = ContentImage.create! valid_attributes
        put :update, params: {id: content_image.to_param, content_image: new_attributes}, session: valid_session
        content_image.reload

        expect(content_image.filename).to eql(new_filename)
      end

      it "assigns the requested content_image as @content_image" do
        content_image = ContentImage.create! valid_attributes
        put :update, params: {id: content_image.to_param, content_image: valid_attributes}, session: valid_session
        expect(assigns(:content_image)).to eq(content_image)
      end

      it "redirects to the content_image" do
        content_image = ContentImage.create! valid_attributes
        put :update, params: {id: content_image.to_param, content_image: valid_attributes}, session: valid_session
        expect(response).to redirect_to(content_image)
      end
    end

    context "with invalid params" do
      it "assigns the content_image as @content_image" do
        content_image = ContentImage.create! valid_attributes
        put :update, params: {id: content_image.to_param, content_image: invalid_attributes}, session: valid_session
        expect(assigns(:content_image)).to eq(content_image)
      end

      it "re-renders the 'edit' template" do
        content_image = ContentImage.create! valid_attributes
        put :update, params: {id: content_image.to_param, content_image: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested content_image" do
      content_image = ContentImage.create! valid_attributes
      expect {
        delete :destroy, params: {id: content_image.to_param}, session: valid_session
      }.to change(ContentImage, :count).by(-1)
    end

    it "redirects to the content_images list" do
      content_image = ContentImage.create! valid_attributes
      delete :destroy, params: {id: content_image.to_param}, session: valid_session
      expect(response).to redirect_to(content_images_url)
    end
  end

end
